export const CinematicTimings = {
  // Animation Timeline (in seconds)
  QR_VERIFIED: 0.0,
  AUTHENTICATION_SUCCESS: 0.3,
  BACKGROUND_TRANSITION: 0.5,
  LOGO_GLOW: 1.0,
  SECURITY_ACCESS_GRANTED: 1.5,
  DOOR_APPEARS: 2.0,
  LED_LIGHTS_ACTIVATE: 2.5,
  DOOR_UNLOCK: 3.0,
  VOICE_BEGINS: 3.5,
  DOOR_OPENS: 4.5,
  CAMERA_MOVES: 5.5,
  RECEPTIONIST_VISIBLE: 6.5,
  DASHBOARD_APPEARS: 7.5,
  EXPERIENCE_COMPLETE: 8.0,
};
